version: 2

updates:
  - package-ecosystem: bundler
    directory: /

    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /

    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /noodles_gff-rb

    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /noodles_gff-rb

    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /schema

    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /web

    schedule:
      interval: daily

    groups:
      types:
        patterns:
          - '@types/*'
