name: repository

services:
  validator:
    image: ghcr.io/ddbj/ddbj_validator:main
    container_name: repository-validator
    ports:
      - 3001:3000
    volumes:
      - ./validator/logs:/usr/src/ddbj_validator/logs
      - ./validator/conf/pub:/usr/src/ddbj_validator/conf/pub
      - ./validator/conf/coll_dump:/usr/src/ddbj_validator/conf/coll_dump
    environment:
      DDBJ_VALIDATOR_APP_VIRTUOSO_ENDPOINT_MASTER: http://repository-virtuoso:8890/sparql
      DDBJ_VALIDATOR_APP_NAMED_GRAPHE_URI_TAXONOMY: http://ddbj.nig.ac.jp/ontologies/taxonomy-private
    depends_on:
      - virtuoso

  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.6-r1-g0a3336c
    container_name: repository-virtuoso
    volumes:
      - ./validator/virtuoso/database:/database

  seaweedfs:
    image: chrislusf/seaweedfs
    container_name: repository-seaweedfs
    ports:
      - 8333:8333
    volumes:
      - seaweedfs:/data
      - ./docker/seaweedfs/entrypoint.sh:/entrypoint.sh
      - ./docker/seaweedfs/s3.development.json:/etc/seaweedfs/s3.json
    entrypoint: /entrypoint.sh

  keycloak:
    image: keycloak/keycloak:26.3.1
    container_name: repository-keycloak
    ports:
      - 8080:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: keycloak
      KC_BOOTSTRAP_ADMIN_PASSWORD: keycloak
    volumes:
      - keycloak:/opt/keycloak/data
    command: start-dev

volumes:
  seaweedfs:
  keycloak:
