namespace :db do
  desc 'Run migrations'
  task :migrate, [:version] do |t, args|
    require 'sequel/core'

    Sequel.extension :migration

    Sequel.connect ENV.fetch('DATABASE_URL') do |db|
      Sequel::Migrator.run db, 'db/migrations', target: args[:version]&.to_i
    end
  end
end
