default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  primary:
    <<: *default
    database: repository_development
  queue:
    <<: *default
    database: repository_development_queue
    migrations_paths: db/queue_migrate
  taxdump:
    <<: *default
    database: taxdump_development
    migrations_paths: db/taxdump_migrate

test:
  primary:
    <<: *default
    database: repository_test
  taxdump:
    <<: *default
    database: taxdump_test
    migrations_paths: db/taxdump_migrate

production: &production
  primary:
    <<: *default
    url: <%= Rails.application.credentials.dig(:database_url, :primary) %>
  cache:
    <<: *default
    url: <%= Rails.application.credentials.dig(:database_url, :cache) %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= Rails.application.credentials.dig(:database_url, :queue) %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= Rails.application.credentials.dig(:database_url, :cable) %>
    migrations_paths: db/cable_migrate
  taxdump:
    <<: *default
    url: <%= Rails.application.credentials.dig(:database_url, :taxdump) %>
    migrations_paths: db/taxdump_migrate

staging:
  <<: *production

dev:
  <<: *production
