- id: BioProject
  objects:
    - id: BioProject
      validator: ddbj_validator
      param_name: biosample

- id: BioSample
  objects:
    - id: BioSample
      validator: ddbj_validator
      param_name: biosample

- id: Trad
  objects:
    - id: Sequence
    - id: Annotation

- id: DRA
  objects:
    - id: Submission
    - id: Experiment
    - id: Run
    - id: RunFile
    - id: Analysis
    - id: AnalysisFile

- id: GEA
  objects:
    - id: IDF
    - id: SDRF
    - id: ADF
    - id: RawDataFile
    - id: ProcessedDataFile

- id: MetaboBank
  objects:
    - id: IDF
    - id: SDRF
    - id: MAF
    - id: RawDataFile
    - id: ProcessedDataFile

- id: JVar
  objects:
    - id: Study
    - id: SampleSet
    - id: Sample
    - id: Experiment
    - id: Assay
    - id: VariantCallSV
    - id: VariantRegionSV
    - id: VariantCallFile
