- id: BioProject
  validator: bioproject

  objects:
    - id: BioProject

- id: BioSample
  validator: biosample

  objects:
    - id: BioSample

- id: Trad
  objects:
    - id: Sequence
    - id: Annotation

- id: DRA
  validator: dra
  objects:
    - id: Submission
    - id: Experiment
    - id: Run
    - id: RunFile
    - id: Analysis
      optional: true
    - id: AnalysisFile
      optional: true

- id: GEA
  objects:
    - id: IDF
    - id: SDRF
    - id: ADF
      optional: true
    - id: RawDataFile
    - id: ProcessedDataFile
      optional: true

- id: MetaboBank
  objects:
    - id: IDF
    - id: SDRF
    - id: MAF
      optional: true
    - id: RawDataFile
    - id: ProcessedDataFile
      optional: true

- id: JVar
  objects:
    - id: Study
    - id: SampleSet
    - id: Sample
    - id: Experiment
    - id: Assay
    - id: VariantCallSV
    - id: VariantRegionSV
    - id: VariantCallFile
      optional: true
