servers:
  web:
    hosts:
      - repository-production

proxy:
  host: repository.ddbj.nig.ac.jp

volumes:
  - ./volumes/repository-production/storage:/rails/storage

builder:
  args:
    API_URL: https://repository.ddbj.nig.ac.jp/api

accessories:
  minio:
    host: repository-production

    proxy:
      host: repository-storage.ddbj.nig.ac.jp

    volumes:
      - ./volumes/repository-production/minio:/data

  virtuoso:
    host: repository-production

    volumes:
      - ./volumes/repository-production/virtuoso:/database

  validator:
    host: repository-production

    env:
      clear:
        DDBJ_VALIDATOR_APP_POSTGRES_HOST: a011

    volumes:
      - ./volumes/repository-production/validator/conf/pub:/usr/src/ddbj_validator/conf/pub
      - ./volumes/repository-production/validator/conf/coll_dump:/usr/src/ddbj_validator/conf/coll_dump
      - ./volumes/repository-production/validator/logs:/usr/src/ddbj_validator/logs
