servers:
  web:
    hosts:
      - repository-staging

proxy:
  host: repository-staging.ddbj.nig.ac.jp

env:
  clear:
    RAILS_ENV: staging

volumes:
  - ./volumes/repository-staging/storage:/rails/storage

builder:
  args:
    API_URL: https://repository-staging.ddbj.nig.ac.jp/api

accessories:
  postgres:
    host: repository-staging

    volumes:
      - ./volumes/repository-staging/postgres:/var/lib/postgresql/data

  minio:
    host: repository-staging

    proxy:
      host: repository-storage-staging.ddbj.nig.ac.jp

    volumes:
      - ./volumes/repository-staging/minio:/data

  virtuoso:
    host: repository-staging

    volumes:
      - ./volumes/repository-staging/virtuoso:/database

  validator:
    host: repository-staging

    env:
      clear:
        DDBJ_VALIDATOR_APP_POSTGRES_HOST: a012

    volumes:
      - ./volumes/repository-staging/validator/conf/pub:/usr/src/ddbj_validator/conf/pub
      - ./volumes/repository-staging/validator/conf/coll_dump:/usr/src/ddbj_validator/conf/coll_dump
      - ./volumes/repository-staging/validator/logs:/usr/src/ddbj_validator/logs
