development:
  endpoint:   http://localhost:8333
  bucket:     repository
  access_key: <%= ENV['SEAWEEDFS_ACCESS_KEY'] %>
  secret_key: <%= ENV['SEAWEEDFS_SECRET_KEY'] %>

production: &production
  endpoint:   https://repository-storage.ddbj.nig.ac.jp
  bucket:     uploads
  access_key: <%= Rails.application.credentials.dig(:seaweedfs, :access_key) %>
  secret_key: <%= Rails.application.credentials.dig(:seaweedfs, :secret_key) %>

staging:
  <<: *production
  endpoint: https://repository-storage-staging.ddbj.nig.ac.jp

dev:
  <<: *production
  endpoint: https://repository-storage-dev.ddbj.nig.ac.jp
