max_retries: 12 # About < 12 hours. Ref: https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry

:scheduler:
  :schedule:
    DestroyStaledRequestsJob:
      cron: '0 0 3 * * *'
    PurgeUnattachedUploadsJob:
      cron: '0 5 3 * * *'
