shared:
  path: <%= Rails.root.join('storage/taxdump.tar.gz') %>

production: &production
  path: /ddbjshare/public/mirror_database/ftp.ncbi.nih.gov/ncbi_taxonomy/taxonomydb/taxdump.tar.gz

staging:
  <<: *production

dev:
  <<: *production
