volumes:
  postgres:
  redis:

services:
  rails: &rails
    build:
      context: ..

      args:
        APP_GID:
        APP_UID:
        RUBY_VERSION:

    environment:
      DATABASE_URL:    postgresql://postgres@postgres/ddbj_repository
      HTTP_PORT:
      REDIS_URL:       redis://redis
      REPOSITORY_DIR:  /repository
      SECRET_KEY_BASE:
      STAGE:

    ports:
      - ${HTTP_PORT:?}:3000

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  sidekiq:
    <<: *rails
    command: [bundle, exec, sidekiq]
    ports: []

  postgres:
    image: postgres:16

    environment:
      POSTGRES_DB:               ddbj_repository
      POSTGRES_HOST_AUTH_METHOD: trust

    volumes:
      - postgres:/var/lib/postgresql/data

    healthcheck:
      test: [CMD, pg_isready, --username, postgres]
      interval: 1s
      timeout: 3s
      retries: 30

  redis:
    image: redis:7
    command: [--appendonly, 'yes']

    volumes:
      - redis:/data

    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 1s
      timeout: 3s
      retries: 30
