services:
  rails: &rails-local
    environment:
      DISABLE_SSL: 'true'

    extra_hosts:
      - keycloak.localhost:host-gateway
      - ddbj-repository.localhost:host-gateway

    volumes:
      - ../api/tmp/home:/data/home
      - ../api/tmp/repository:/data/repository

  solid_queue:
    <<: *rails-local

  minio:
    ports:
      - 9000:9000
      - 9001:9001
