volumes:
  postgres:
  minio:

services:
  rails:
    extra_hosts:
      - repository.localhost:host-gateway

    volumes:
      - ../api/tmp/home:/data/home
      - ../api/tmp/repository:/data/repository

    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started

  postgres:
    image: postgres:16

    environment:
      POSTGRES_DB: repository
      POSTGRES_HOST_AUTH_METHOD: trust

    volumes:
      - postgres:/var/lib/postgresql/data

    healthcheck:
      test: [CMD-SHELL, pg_isready]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    command: [server, /data]

    volumes:
      - minio:/data
