services:
  rails: &rails-local
    environment:
      DISABLE_SSL: 'true'

    extra_hosts:
      - host.docker.internal:host-gateway
      - keycloak.localhost:host-gateway
      - ddbj-repository.localhost:host-gateway

    volumes:
      - ../api/tmp/home:/data/home
      - ../api/tmp/repository:/data/repository

  solid_queue:
    <<: *rails-local
