services:
  rails: &rails
    group_add:
      - '60000' # submitter

    volumes:
      - type: bind
        source: ~/repository/$STAGE
        target: /data/repository
      - type: bind
        source: /home
        target: /data/home

  solid_queue:
    <<: *rails

  postgres:
    volumes:
      - type: bind
        source: ~/ddbj-repository/data/$STAGE/postgres
        target: /var/lib/postgresql/data

  minio:
    volumes:
      - type: bind
        source: ~/ddbj-repository/data/$STAGE/minio
        target: /data

  virtuoso:
    volumes:
      - type: bind
        source: ~/ddbj-repository/data/$STAGE/virtuoso
        target: /database
