services:
  rails: &rails
    group_add:
      - '60000' # submitter
    volumes:
      - type: bind
        source: ~/ddbj-repository/data/$STAGE/storage
        target: /rails/storage
      - type: bind
        source: ~/repository-$STAGE
        target: /mnt/repository
      - type: bind
        source: /home
        target: /mnt/home

  sidekiq:
    <<: *rails

  postgres:
    volumes:
      - type: bind
        source: ~/ddbj-repository/data/$STAGE/postgres
        target: /var/lib/postgresql/data

  redis:
    volumes:
      - type: bind
        source: ~/ddbj-repository/data/$STAGE/redis
        target: /data
