services:
  rails: &rails
    group_add:
      - '60000' # submitter

    volumes:
      - type: bind
        source: ~/repository/$STAGE
        target: /data/repository
      - type: bind
        source: /home
        target: /data/home

    restart: unless-stopped

  solid_queue:
    <<: *rails

networks:
  default:
    external: true
    name: repository-$STAGE
