/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api_key/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Re-generate API key. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns a new API key. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            api_key: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get your information. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            uid: string;
                            api_key: string;
                            admin: boolean;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submission_requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a list of submission requests. Omit `db` to span every database the user has access to. */
        get: {
            parameters: {
                query?: {
                    db?: components["schemas"]["Db"];
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the list of submission requests. */
                200: {
                    headers: {
                        "Total-Pages"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionRequestSummary"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** @description Create a submission request. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        submission_request: {
                            db: components["schemas"]["Db"];
                            /** Format: binary */
                            ddbj_record: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Accepted the submission request creation. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionRequest"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["UnprocessableContent"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submission_requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** @description Get a submission request. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the requested submission request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionRequest"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submission_requests/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** @description Get the status of a submission request. Lightweight endpoint for polling. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the status of the submission request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionRequestStatus"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submission_requests/{id}/submission": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Apply a submission request. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted the submission request application. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["UnprocessableContent"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a list of submissions. Omit `db` to span every database the user has access to. */
        get: {
            parameters: {
                query?: {
                    db?: components["schemas"]["Db"];
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the list of submissions. */
                200: {
                    headers: {
                        "Total-Pages"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionSummary"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** @description Get a submission. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the requested submission. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Submission"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}/accessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** @description Get a paginated list of accessions for a submission. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the list of accessions. */
                200: {
                    headers: {
                        "Total-Pages"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Accession"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accessions/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get an accession by number, including its submission and flatfile URLs. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    number: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the accession with its submission. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            number: string;
                            entry_id: string;
                            version: number;
                            /** Format: date */
                            locus_date: string;
                            submission: components["schemas"]["Submission"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Db: "st26" | "bioproject" | "biosample";
        SubmissionRequestSummary: {
            id: number;
            db: components["schemas"]["Db"];
            status: components["schemas"]["SubmissionOperationStatus"];
            /** Format: date-time */
            created_at: string;
            submission_id: number | null;
            has_accession: boolean;
        };
        SubmissionRequestStatus: {
            id: number;
            status: components["schemas"]["SubmissionOperationStatus"];
            error_message: string | null;
            processing: boolean;
        };
        SubmissionRequest: {
            id: number;
            status: components["schemas"]["SubmissionOperationStatus"];
            error_message: string | null;
            /** Format: date-time */
            created_at: string;
            processing: boolean;
            ddbj_record: components["schemas"]["Attachment"];
            validation: components["schemas"]["Validation"] | null;
            submission: components["schemas"]["Submission"] | null;
        };
        Validation: {
            id: number;
            /** @enum {string} */
            progress: "running" | "finished" | "canceled";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at: string | null;
            /** @enum {string|null} */
            validity: "valid" | "invalid" | null;
            details: {
                entry_id: string | null;
                code: string;
                /** @enum {string} */
                severity: "warning" | "error";
                message: string;
            }[];
        };
        SubmissionSummary: {
            id: number;
            db: components["schemas"]["Db"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Submission: {
            id: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            ddbj_record: components["schemas"]["Attachment"];
            flatfile_na: components["schemas"]["Attachment"] | null;
            flatfile_aa: components["schemas"]["Attachment"] | null;
        };
        Accession: {
            number: string;
            entry_id: string;
            version: number;
            /** Format: date */
            locus_date: string;
        };
        Attachment: {
            filename: string;
            /** Format: uri */
            url: string;
        };
        /** @enum {string} */
        SubmissionOperationStatus: "waiting_validation" | "validating" | "validation_failed" | "ready_to_apply" | "waiting_application" | "applying" | "applied" | "application_failed" | "no_change";
        Error: {
            error: string;
        };
    };
    responses: {
        /** @description Unexpected parameter specified. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not authenticated. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Does not have access rights to the resource. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested resource could not be found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid parameter or payload was specified. */
        UnprocessableContent: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
