/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api_key/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Re-generate API key. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns a new API key. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            api_key: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get your information. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            uid: string;
                            api_key: string;
                            admin: boolean;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Get the requests that are waiting on the current user: a file that
         *     stopped on a validation error, one that passed validation and is
         *     waiting to be applied, or an unanswered curator question. Used for
         *     a global banner, so the notice is visible from any screen rather
         *     than only where the request happens to be listed.
         *
         *     A failed *application* is deliberately not here — that one is
         *     DDBJ's to fix, and asking the submitter to act on it only makes
         *     them resubmit a file that was fine.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the requests needing attention, newest first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            requests: {
                                id: number;
                                db: components["schemas"]["Db"];
                                source_id: string | null;
                                /**
                                 * @description Why this request is waiting on the submitter,
                                 *     most-blocking first when it is more than one.
                                 * @enum {string}
                                 */
                                reason: "validation_failed" | "ready_to_apply" | "unread_message";
                            }[];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submission_requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Get a list of submission requests. `db` and `status` are multi-select
         *     filters (repeat the key, e.g. `?db[]=st26&db[]=biosample`); omit a
         *     filter to span every value. `source_id` is a case-insensitive prefix
         *     match on the applied submission's source id. `accession` is a
         *     case-insensitive prefix match across the submission's accessions
         *     (BP project / BS samples / ST.26 accessions).
         *
         *     `phase` splits the live submissions from the finished ones and
         *     defaults to `unfinished`; `needs_action` narrows to the ones
         *     waiting on the submitter (the same set `/attention` returns).
         *     `Unfinished-Count` and `Finished-Count` report both halves
         *     regardless of which one is being listed.
         */
        get: {
            parameters: {
                query?: {
                    "db[]"?: components["schemas"]["Db"][];
                    "status[]"?: components["schemas"]["SubmissionOperationStatus"][];
                    source_id?: string;
                    accession?: string;
                    phase?: "unfinished" | "finished" | "all";
                    needs_action?: boolean;
                    needs_action_first?: boolean;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the list of submission requests. */
                200: {
                    headers: {
                        "Total-Pages"?: string;
                        "Unfinished-Count"?: string;
                        "Finished-Count"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionRequestSummary"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** @description Create a submission request. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        submission_request: {
                            db: components["schemas"]["Db"];
                            /** Format: binary */
                            ddbj_record: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Accepted the submission request creation. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionRequest"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["UnprocessableContent"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submission_requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** @description Get a submission request. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the requested submission request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionRequest"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submission_requests/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** @description Get the status of a submission request. Lightweight endpoint for polling. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the status of the submission request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionRequestStatus"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submission_requests/{id}/closure": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Close a submission request — "I am not taking this one further".
         *
         *     A request that failed validation cannot be advanced: a corrected file
         *     arrives as a new request with no link back to this one, so closing is
         *     the only way it ever reaches an end. The request keeps its status, its
         *     validation and its messages; it stops asking the submitter for
         *     something and moves to the finished side of the list.
         *
         *     Only a request that is asking for something may be closed (validation
         *     failed, or ready to apply) — see `closable`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the closed submission request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionRequest"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description The request is not in a state that can be closed. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        /**
         * @description Reopen a closed submission request. As cheap as closing it, because
         *     closing undoes nothing.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the reopened submission request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionRequest"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submission_requests/{id}/submission": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Apply a submission request. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted the submission request application. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["UnprocessableContent"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submission_requests/{submission_request_id}/reviewer_access": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_request_id: number;
            };
            cookie?: never;
        };
        /** @description Get the reviewer-access link state for a request. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    submission_request_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Whether reviewer access is enabled and, if so, its share URL and expiry. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewerAccess"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** @description Enable reviewer access, minting a fresh unguessable link. Any existing link is invalidated. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    submission_request_id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reviewer_access: {
                            /** Format: date-time */
                            expires_at: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Returns the newly-enabled reviewer access. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewerAccess"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["UnprocessableContent"];
            };
        };
        /** @description Disable reviewer access, invalidating the link. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    submission_request_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reviewer access disabled. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        /** @description Reviewer view of a submission request via its share token. No authentication; messages are deliberately not included. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the submission request. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewerSubmissionRequest"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{token}/accessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        /** @description Reviewer view of a submission's accessions via the share token. No authentication. */
        get: {
            parameters: {
                query?: {
                    page?: number;
                };
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the list of accessions. */
                200: {
                    headers: {
                        "Total-Pages"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReviewerAccession"][];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a list of submissions. Omit `db` to span every database the user has access to. */
        get: {
            parameters: {
                query?: {
                    db?: components["schemas"]["Db"];
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the list of submissions. */
                200: {
                    headers: {
                        "Total-Pages"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubmissionSummary"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** @description Get a submission. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the requested submission. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Submission"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}/accessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /**
         * @description Get a paginated list of accessions for a submission. `status`
         *     filters it, the same way it does on `/accessions` — the two share
         *     the action, so leaving it undocumented here would mean a client
         *     relying on behaviour no test defends.
         */
        get: {
            parameters: {
                query?: {
                    "status[]"?: components["schemas"]["CurationStatus"][];
                    page?: number;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the list of accessions. */
                200: {
                    headers: {
                        "Total-Pages"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Accession"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submission_requests/{submission_request_id}/messages/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_request_id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Mark the curator's messages in this thread as read — "nothing to answer
         *     here".
         *
         *     Reading the thread does not do this. "I have seen it" and "I have dealt
         *     with it" are different events, and a submitter who opens a question
         *     meaning to answer it later should keep the reminder. Replying discharges
         *     the thread too; this is for the note that needs no reply.
         *
         *     `through_id` is the newest message the client had in front of it. One
         *     that arrives a moment later is not acknowledged by a press that could
         *     not have taken it into account. Omit it to mark the whole thread.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    submission_request_id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        through_id?: number;
                    };
                };
            };
            responses: {
                /** @description The curator's messages are marked read. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submission_requests/{submission_request_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_request_id: number;
            };
            cookie?: never;
        };
        /** @description Get the curator ↔ submitter message thread for a request. Marks any unread curator-authored messages as read. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    submission_request_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the chronological list of messages. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** @description Submitter posts a reply to the thread. Notifies curators by email. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    submission_request_id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        submission_message: {
                            body: string;
                            /**
                             * @description Signed ids from ActiveStorage direct upload. The file goes
                             *     to storage from the browser, so nothing here is bounded by
                             *     this request — the files this conversation is about are
                             *     submission files, which are large by nature.
                             */
                            files?: string[];
                        };
                    };
                };
            };
            responses: {
                /** @description Returns the newly-created message. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["UnprocessableContent"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Get a paginated list of every accession the caller has, across
         *     submissions. `status` is a multi-select filter (repeat the key,
         *     e.g. `?status[]=canceled&status[]=withdrawn`); omit it to span
         *     every value.
         *
         *     Narrowing by status is what this is for. A client holding a local
         *     copy of every entry it registered rebuilds its lists from that
         *     copy, so it has to hear about a retraction it did not make — and
         *     those are a handful of rows among millions. Asking for them a
         *     submission at a time is one walk per submission.
         *
         *     Paginated 1000 at a time rather than the usual 20: a page of this
         *     is read by a script keeping a copy in step, not by a person.
         *
         *     Walked with a cursor rather than a page number. Offset pagination
         *     is wrong for a walk rather than merely slow: a row that disappears
         *     from a page already read pulls every later row back one place, and
         *     the row on the far side of the boundary is never returned. Pass
         *     the `Next-Page` header of the previous response back as `page`;
         *     its absence means there is nothing after this page. There is no
         *     total.
         */
        get: {
            parameters: {
                query?: {
                    "status[]"?: components["schemas"]["CurationStatus"][];
                    /** @description Opaque cursor from the previous response's `Next-Page` header. Omit for the first page. */
                    page?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the list of accessions. */
                200: {
                    headers: {
                        /** @description Cursor for the next page. Absent on the last one. */
                        "Next-Page"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Accession"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accessions/{number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get an accession by number, including its submission and flatfile URLs. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    number: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the accession with its submission. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            accession: string;
                            status: components["schemas"]["CurationStatus"];
                            entry_id: string;
                            version: number;
                            /** Format: date */
                            locus_date: string;
                            submission: components["schemas"]["Submission"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Sets you belong to. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every set this account has joined. Outstanding invitations are not membership and do not appear here. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SetSummary"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** @description Create a set. You become its owner and its first member. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        set: {
                            name: string;
                        };
                    };
                };
            };
            responses: {
                /** @description The new set. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Set"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Sets cannot be changed while acting as another account. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                422: components["responses"]["UnprocessableContent"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /**
         * @description One set: its roster and a page of the submissions in it. A set you
         *     are not in answers 404 rather than 403 — from outside, it is not a
         *     set you have an id for.
         *
         *     The roster comes whole (a set is people, and there are not many of
         *     them); the submissions are paginated, because a study that ran for
         *     three years is hundreds of them and each one renders a progress block.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The set. */
                200: {
                    headers: {
                        "Total-Pages"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Set"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /**
         * @description Delete a set. The owner's, and only once everyone else has left and
         *     every submission has been taken out — the submissions are their
         *     owners' to remove, and the people are not the owner's to dissolve.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description The set still has other members or submissions in it. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** @description Rename a set. The owner's, not every member's. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        set: {
                            name: string;
                        };
                    };
                };
            };
            responses: {
                /** @description The renamed set. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Set"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["UnprocessableContent"];
            };
        };
        trace?: never;
    };
    "/sets/{set_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Invite somebody by email. Any member may invite. The mail carries a
         *     single-use link; what is checked on the way in is that link and not
         *     the address, so the recipient may accept with an account registered
         *     at a different address — the roster says so when they do.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    set_id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        set_member: {
                            email: string;
                        };
                    };
                };
            };
            responses: {
                /**
                 * @description The invited member, with the invitation still outstanding. Check
                 *     `mail_deliverable`: where outgoing mail is restricted the invitation
                 *     is real but nobody was told, and `invitation_url` is what to send.
                 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SetMember"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Sets cannot be changed while acting as another account. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["UnprocessableContent"];
                /** @description Too many invitations in a short time. */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/{set_id}/members/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: number;
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Leave, take back an invitation you sent, or (as the owner) remove
         *     somebody. Removing a member takes their submissions out of the set
         *     with them: the set was the only thing letting the others read that
         *     work.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    set_id: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description The owner cannot leave their own set. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/{set_id}/members/{member_id}/reminder": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: number;
                member_id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Send the invitation again. A fresh token and a fresh clock, so the
         *     link that did not get used stops working.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    set_id: number;
                    member_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The member, with a new invitation outstanding. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SetMember"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Sets cannot be changed while acting as another account. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description That person has already joined. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/{set_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Put submissions of yours in the set, which is what lets the set's
         *     members read them. Yours only — reading somebody else's through a
         *     shared set does not carry the right to hand it on, and an id you do
         *     not own answers 404 rather than being quietly dropped.
         *
         *     Always a list; one submission is a list of one. The submitter's list
         *     screen adds a page's worth in a press, and splitting that into one
         *     request each would leave nobody holding the answer to what actually
         *     went in.
         *
         *     Ones already in the set are counted, not refused: ten checkboxes
         *     where three are already there is an ordinary press.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    set_id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        submission_request_ids: number[];
                    };
                };
            };
            responses: {
                /**
                 * @description What happened, as counts. Not the set itself: answering with that
                 *     would mean loading a page of it — a progress block and an accession
                 *     summary per row — for something the client re-reads anyway. Both
                 *     numbers, because "8 added" alone leaves somebody who checked ten
                 *     wondering about the other two.
                 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            added: number;
                            already_in_set: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Sets cannot be changed while acting as another account. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                404: components["responses"]["NotFound"];
                422: components["responses"]["UnprocessableContent"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/{set_id}/submissions/{submission_request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: number;
                submission_request_id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Take your submission back out of the set. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    set_id: number;
                    submission_request_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        /**
         * @description What an invitation link is for, readable without an account — the
         *     person holding it may not have one yet. An expired invitation is
         *     answered rather than hidden: the holder is the intended recipient,
         *     and "ask them to send it again" is the only thing that unsticks them.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The invitation. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invitation"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invitations/{invitation_token}/acceptance": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_token: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Walk through the invitation and join the set. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    invitation_token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /**
                 * @description The set you have joined — or were already in, if this invitation
                 *     was a second one sent to the same person, in which case it is simply
                 *     spent.
                 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SetSummary"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description The invitation has expired, or somebody has already used it. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description How much of each accession space has been handed out, and the state
         *     of the loaded taxonomy. No authentication: these are counts, not
         *     anybody's data.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the sequence and taxdump counters. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            sequences: {
                                scope: string;
                                /**
                                 * @description The number the next allocation will hand out.
                                 *     `null` once every prefix in the space is used
                                 *     up, which is also when `remaining` reaches 0.
                                 */
                                next: string | null;
                                total: number;
                                used: number;
                                remaining: number;
                            }[];
                            taxdump: {
                                names_count: number;
                                nodes_count: number;
                                /**
                                 * Format: date-time
                                 * @description `null` before the first load.
                                 */
                                loaded_at: string | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Db: "st26" | "bioproject" | "biosample";
        SubmissionRequestSummary: {
            id: number;
            db: components["schemas"]["Db"];
            status: components["schemas"]["SubmissionOperationStatus"];
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description The submitter put this request down. A row and the page it opens
             *     answer the same question from the same facts, so the summary
             *     carries it too.
             */
            closed_at: string | null;
            submission_id: number | null;
            source_id: string | null;
            first_accession: string | null;
            accession_count: number;
            /** @description Validation or application is running right now. */
            processing: boolean;
            unread_curator_message_count: number;
            progress: components["schemas"]["Progress"];
        };
        SetSummary: {
            id: number;
            name: string;
            owner_uid: string;
            /** @description You created it, so renaming and deleting it are yours. */
            owned: boolean;
            /** Format: date-time */
            created_at: string;
            /** @description People who have accepted. */
            member_count: number;
            /** @description Invitations still outstanding. */
            invited_count: number;
            submission_count: number;
        };
        Set: {
            id: number;
            name: string;
            owner_uid: string;
            owned: boolean;
            /** Format: date-time */
            created_at: string;
            member_count: number;
            invited_count: number;
            submission_count: number;
            /**
             * @description Whether the set can be deleted now — only once everyone else has
             *     left and every submission has been taken out. Deleting is the
             *     owner's; this says nothing about who you are.
             */
            deletable: boolean;
            /**
             * @description Why it cannot be, in words. Null when it can. Served rather than
             *     re-worded by the client, so the rule and its wording stay together.
             */
            delete_blocked_reason: string | null;
            members: components["schemas"]["SetMember"][];
            submissions: components["schemas"]["SetSubmission"][];
        };
        SetMember: {
            id: number;
            /** @description The address the invitation was sent to. Null on the creator's own row, who was never invited. */
            email: string | null;
            /** @description The account that accepted. Null while the invitation is still out. */
            uid: string | null;
            /**
             * @description `accepted` — they are in. `open` — the invitation is out and live.
             *     `expired` — it lapsed; any member can send it again. The same three
             *     words the invitation page uses, so the roster and the link cannot
             *     describe one row differently.
             * @enum {string}
             */
            status: "open" | "expired" | "accepted";
            owner: boolean;
            you: boolean;
            invited_by: string;
            /** Format: date-time */
            joined_at: string | null;
            /** Format: date-time */
            invitation_expires_at: string | null;
            /**
             * @description Whether you may take this row off the roster — by leaving, by
             *     removing somebody as the owner, or by taking back an invitation you
             *     sent. Stated by the server because the three are different
             *     permissions and, under a proxy login, the account the client
             *     believes it is is not the account the server acts as.
             */
            removable: boolean;
            /**
             * @description How many of this set's submissions are theirs, and would therefore
             *     be taken out of it with them. Counted over the whole set, not over
             *     the page of submissions being shown.
             */
            submission_count: number;
            /**
             * @description Whether the account that walked through the invitation is registered
             *     at the address it was sent to. `unknown` when that account carries
             *     no address at all — most accounts imported from D-way have never
             *     signed in. Null where the question does not arise: the creator's own
             *     row, which was never invited.
             *
             *     A forwarded invitation is a real thing people do, so this is
             *     reported rather than refused — it is the whole of the audit that
             *     pays for not binding the token to the address.
             * @enum {string|null}
             */
            invited_address_match: "same" | "different" | "unknown" | null;
            /**
             * @description The link an outstanding invitation was mailed as. Null once it has
             *     been walked through. Offered to members so they can send it by hand
             *     when the mail did not arrive — which includes every environment
             *     where outgoing mail is restricted (see `mail_deliverable`).
             */
            invitation_url: string | null;
            /**
             * @description Whether the invitation mail actually leaves the building. False in a
             *     deployed environment whose outgoing mail is restricted to DDBJ
             *     addresses, in which case the invitation exists and works but nobody
             *     was told about it — hand them `invitation_url` instead. Null once
             *     the invitation has been walked through.
             */
            mail_deliverable: boolean | null;
        };
        SetSubmission: {
            /** Format: date-time */
            added_at: string;
            /** @description Whose submission this is. In every other list it goes without saying; here it is the first thing a reader needs. */
            owner_uid: string;
            /**
             * @description It is yours, so taking it out of the set is yours to do. Said by
             *     the server for the same reason `removable` is on a member.
             */
            owned: boolean;
            submission: components["schemas"]["SubmissionRequestSummary"];
        };
        Invitation: {
            set_name: string;
            invited_by: string;
            email: string;
            /**
             * Format: date-time
             * @description Null once the invitation has been walked through.
             */
            expires_at: string | null;
            /**
             * @description `open` — ready to be walked through. `expired` — ask a member of the
             *     set to send it again. `accepted` — somebody has already used this
             *     link; the token is kept after acceptance precisely so the page can
             *     say so instead of answering with a 404.
             * @enum {string}
             */
            status: "open" | "expired" | "accepted";
        };
        ReviewerAccess: {
            enabled: boolean;
            url?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        SubmissionRequestStatus: {
            id: number;
            status: components["schemas"]["SubmissionOperationStatus"];
            /**
             * @description Machine-readable reason the application failed. Null until it does.
             *     Branch on this rather than on `error_message`, whose wording changes
             *     without notice. An unknown code means an unexpected internal error;
             *     treat it like `TRD_R9999`.
             */
            error_code: string | null;
            error_message: string | null;
            processing: boolean;
        };
        SubmissionRequest: {
            id: number;
            db: components["schemas"]["Db"];
            status: components["schemas"]["SubmissionOperationStatus"];
            /**
             * @description Machine-readable reason the application failed. Null until it does.
             *     Branch on this rather than on `error_message`, whose wording changes
             *     without notice. An unknown code means an unexpected internal error;
             *     treat it like `TRD_R9999`.
             */
            error_code: string | null;
            error_message: string | null;
            /** Format: date-time */
            created_at: string;
            /**
             * @description The sets this submission has been shared into. Withheld from the
             *     reviewer view — somebody holding a share link is not party to who
             *     else is working on this.
             */
            sets: {
                id: number;
                name: string;
            }[];
            /**
             * Format: date-time
             * @description When the submitter put this request down. A request that failed
             *     validation cannot be advanced — a corrected file arrives as a new
             *     request — so closing is the only way it reaches an end. Null while
             *     it is still open.
             */
            closed_at: string | null;
            /**
             * @description Whether you may close it now. True only while the request is asking
             *     its owner for something (validation failed, or ready to apply) —
             *     and never for somebody reading it through a shared set.
             */
            closable: boolean;
            /**
             * @description You are the submitter. False when you are reading this through a
             *     set somebody else's submission was shared into, in which case
             *     nothing on the page is yours to press and the conversation facts
             *     are withheld.
             */
            owned: boolean;
            /**
             * @description Whose submission this is. Yours when `owned`; otherwise the
             *     colleague whose work you are reading through a shared set — the
             *     page says so rather than addressing you as its submitter.
             */
            owner_uid: string;
            processing: boolean;
            ddbj_record: components["schemas"]["Attachment"];
            validation: components["schemas"]["Validation"] | null;
            submission: components["schemas"]["Submission"] | null;
            progress: components["schemas"]["Progress"];
            unread_curator_message_count: number;
            /**
             * Format: date-time
             * @description When the thread was last posted to, by either party.
             */
            last_message_at: string | null;
        };
        /**
         * @description What a share-link holder may see. Identical to SubmissionRequest
         *     minus the messaging facts: the endpoint is unauthenticated, so it
         *     must not disclose that a curator ↔ submitter conversation exists.
         *     Spelled out rather than derived from SubmissionRequest because
         *     `additionalProperties: false` does not compose through `allOf` —
         *     which also means a field added to the submitter view stays out of
         *     this one until somebody decides it belongs here.
         */
        ReviewerSubmissionRequest: {
            id: number;
            db: components["schemas"]["Db"];
            status: components["schemas"]["SubmissionOperationStatus"];
            /**
             * @description Machine-readable reason the application failed. Null until it does.
             *     Branch on this rather than on `error_message`, whose wording changes
             *     without notice. An unknown code means an unexpected internal error;
             *     treat it like `TRD_R9999`.
             */
            error_code: string | null;
            error_message: string | null;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description The submitter put this request down. Null while it is still open.
             */
            closed_at: string | null;
            processing: boolean;
            ddbj_record: components["schemas"]["Attachment"];
            validation: components["schemas"]["Validation"] | null;
            submission: components["schemas"]["Submission"] | null;
            progress: components["schemas"]["Progress"];
        };
        /**
         * @description How far along the request is, in a vocabulary a submitter can read.
         *     Derived server-side from the ingest status and the curation rows —
         *     neither of the underlying enums is a progress scale on its own.
         */
        Progress: {
            /** @enum {string} */
            step: "submitted" | "validated" | "applied" | "curating" | "accession_issued" | "public";
            /** @description The pipeline stopped at the step after `step`. */
            failed: boolean;
            /**
             * @description The record left the pipeline — withdrawn, canceled or
             *     permanently suppressed. `step` is then where it stopped, not
             *     where work is in progress.
             */
            closed: boolean;
            /** @description Curation rows behind the request — 1 project (BP), N samples (BS), 0 otherwise. */
            row_count: number;
            accessioned_count: number;
            /**
             * Format: date
             * @description Scheduled release date. Only BioProject carries one.
             */
            hold_date: string | null;
        };
        Validation: {
            id: number;
            /** @enum {string} */
            progress: "running" | "finished" | "canceled";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at: string | null;
            /** @enum {string|null} */
            validity: "valid" | "invalid" | null;
            details: {
                entry_id: string | null;
                code: string;
                /** @enum {string} */
                severity: "warning" | "error";
                message: string;
            }[];
        };
        SubmissionSummary: {
            id: number;
            db: components["schemas"]["Db"];
            source_id: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Submission: {
            id: number;
            source_id: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            accessions_count: number;
            ddbj_record: components["schemas"]["Attachment"];
            flatfile_na: components["schemas"]["Attachment"] | null;
            flatfile_aa: components["schemas"]["Attachment"] | null;
        };
        Accession: {
            accession: string;
            entry_id: string;
            status: components["schemas"]["CurationStatus"];
            version: number;
            /** Format: date */
            locus_date: string;
        };
        Attachment: {
            filename: string;
            /**
             * Format: uri
             * @description Where to fetch the file. Good for one fetch, soon: it redirects to
             *     a storage URL that expires in minutes, and the redirect itself is
             *     authorised when it is followed — by the same rule that let you read
             *     the record it hangs off.
             *
             *     So it is not a thing to store. A link kept from yesterday's listing
             *     does not work, and one handed to somebody else does not work for
             *     them, which is what makes access that has been taken away actually
             *     gone.
             */
            url: string;
        };
        /**
         * @description One file attached to a message. Uploaded directly to storage, so no
         *     size limit is imposed here — the files this conversation is about are
         *     submission files, which are large by nature.
         */
        AttachedFile: {
            filename: string;
            byte_size: number;
            /**
             * @description Where to fetch the file. Good for one fetch, soon: it redirects to
             *     a storage URL that expires in minutes, and the redirect itself is
             *     authorised when it is followed — by the same rule that let you read
             *     the record it hangs off.
             *
             *     So it is not a thing to store. A link kept from yesterday's listing
             *     does not work, and one handed to somebody else does not work for
             *     them, which is what makes access that has been taken away actually
             *     gone.
             */
            url: string;
        };
        Message: {
            id: number;
            body: string;
            /** @enum {string} */
            author_role: "curator" | "submitter";
            author_uid: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            read_at: string | null;
            files: components["schemas"]["AttachedFile"][];
        };
        /** @description What a share-token holder sees of an entry. Deliberately narrower than Accession: the token is unauthenticated, and where the entry stands in DDBJ's own handling of the submission is not a reviewer's business — the same reason the message thread is unreachable from a share link. */
        ReviewerAccession: {
            accession: string;
            entry_id: string;
            version: number;
            /** Format: date */
            locus_date: string;
        };
        /**
         * @description Where a curated row stands. `canceled` and `withdrawn` mean the row is no longer part of the submission: it is left out of the flatfile the next time one is generated, and should be left out of anything derived from it. The stored flatfile still contains it until then — the status is what changed, and regenerating is a separate run.
         * @enum {string}
         */
        CurationStatus: "submission_accepted" | "curating" | "accession_issued" | "private" | "public" | "withdrawn" | "canceled" | "permanently_suppressed" | "temporarily_suppressed";
        /** @enum {string} */
        SubmissionOperationStatus: "waiting_validation" | "validating" | "validation_failed" | "ready_to_apply" | "waiting_application" | "applying" | "applied" | "application_failed" | "no_change";
        Error: {
            error: string;
        };
    };
    responses: {
        /** @description Unexpected parameter specified. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not authenticated. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Does not have access rights to the resource. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested resource could not be found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid parameter or payload was specified. */
        UnprocessableContent: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
