require 'fileutils'
require 'json'
require 'pathname'
require 'yaml'

class Schema < Thor
  include Thor::Actions

  DIR = Pathname.new(__dir__)

  def self.exit_on_failure? = true

  desc 'generate', 'Generate schemas'
  def generate
    dbs = YAML.load_file(DIR.join('db.yml'), symbolize_names: true)
    erb = ERB.new(DIR.join('openapi.yml.erb').read, trim_mode: '-')

    DIR.join('db.json').write JSON.pretty_generate(dbs)
    DIR.join('openapi.yml').write erb.result_with_hash(dbs:)
  end
end
