require 'json'
require 'yaml'

class Schema < Thor
  include Thor::Actions

  def self.exit_on_failure? = true
  def self.source_root      = __dir__

  desc 'generate', 'Generate schemas'
  def generate
    inside __dir__ do
      generate_openapi
    end
  end

  private

  def generate_openapi
    run 'pnpm exec openapi-typescript openapi.yml --output openapi.d.ts'
  end
end
