# vim: ft=ruby

require 'json'
require 'yaml'

class Schema < Thor
  include Thor::Actions

  def self.exit_on_failure? = true
  def self.source_root      = __dir__

  desc 'generate', 'Generate schemas'
  def generate
    inside __dir__ do
      dbs = YAML.load_file('db.yml', symbolize_names: true)

      generate_db      dbs
      generate_openapi dbs
    end
  end

  private

  def generate_db(dbs)
    template 'db.ts', dbs: dbs
  end

  def generate_openapi(dbs)
    erb = ERB.new(File.read('openapi.yml.erb'), trim_mode: '-')

    File.write 'openapi.yml', erb.result_with_hash(dbs:)
    run 'pnpm exec openapi-typescript openapi.yml --output openapi.d.ts'
  end
end
