default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: ddbj_repository_development

  bioproject:
    <<: *default
    database: bioproject_development
    migrations_paths: db/bioproject_migrate

  biosample:
    <<: *default
    database: biosample_development
    migrations_paths: db/biosample_migrate

  drmdb:
    <<: *default
    database: drmdb_development
    migrations_paths: db/drmdb_migrate

  submitterdb:
    <<: *default
    database: submitterdb_development
    migrations_paths: db/submitterdb_migrate

test:
  primary:
    <<: *default
    database: ddbj_repository_test

  bioproject:
    <<: *default
    database: bioproject_test
    migrations_paths: db/bioproject_migrate

  biosample:
    <<: *default
    database: biosample_test
    migrations_paths: db/biosample_migrate

  drmdb:
    <<: *default
    database: drmdb_test
    migrations_paths: db/drmdb_migrate

  submitterdb:
    <<: *default
    database: submitterdb_test
    migrations_paths: db/submitterdb_migrate

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  bioproject:
    <<: *default
    url: <%= ENV["BIOPROJECT_DATABASE_URL"] %>
    database_tasks: false

  biosample:
    <<: *default
    url: <%= ENV["BIOSAMPLE_DATABASE_URL"] %>
    database_tasks: false

  drmdb:
    <<: *default
    url: <%= ENV["DRMDB_DATABASE_URL"] %>
    database_tasks: false

  submitterdb:
    <<: *default
    url: <%= ENV["SUBMITTERDB_DATABASE_URL"] %>
    database_tasks: false
