default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

dway_default: &dway_default
  <<: *default
  schema_search_path: mass,public
  default_timezone: local

bioproject_default: &bioproject_default
  <<: *dway_default
  migrations_paths: db/bioproject_migrate

biosample_default: &biosample_default
  <<: *dway_default
  migrations_paths: db/biosample_migrate

drmdb_default: &drmdb_default
  <<: *dway_default
  migrations_paths: db/drmdb_migrate

submitterdb_default: &submitterdb_default
  <<: *dway_default
  migrations_paths: db/submitterdb_migrate

development:
  primary:
    <<: *default
    database: ddbj_repository_development

  bioproject:
    <<: *bioproject_default
    database: bioproject_development

  biosample:
    <<: *biosample_default
    database: biosample_development

  drmdb:
    <<: *drmdb_default
    database: drmdb_development

  submitterdb:
    <<: *submitterdb_default
    database: submitterdb_development

test:
  primary:
    <<: *default
    database: ddbj_repository_test

  bioproject:
    <<: *bioproject_default
    database: bioproject_test

  biosample:
    <<: *biosample_default
    database: biosample_test

  drmdb:
    <<: *drmdb_default
    database: drmdb_test

  submitterdb:
    <<: *submitterdb_default
    database: submitterdb_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  bioproject:
    <<: *bioproject_default
    url: <%= ENV["DATABASE_URL_BIOPROJECT"] %>
    database_tasks: false

  biosample:
    <<: *biosample_default
    url: <%= ENV["DATABASE_URL_BIOSAMPLE"] %>
    database_tasks: false

  drmdb:
    <<: *drmdb_default
    url: <%= ENV["DATABASE_URL_DRMDB"] %>
    database_tasks: false

  submitterdb:
    <<: *submitterdb_default
    url: <%= ENV["DATABASE_URL_SUBMITTERDB"] %>
    database_tasks: false
