service: repository
image: w3const/repository
require_destination: true

servers:
  web:
    options:
      group-add: 60000

registry:
  username: w3const

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - DATABASE_URL
    - DATABASE_URL_DRASEARCH
    - DATABASE_URL_DWAY
    - MINIO_ACCESS_KEY_ID
    - MINIO_SECRET_ACCESS_KEY
    - SECRET_KEY_BASE
    - SENTRY_DSN

  clear:
    MASS_DIR_PATH_TEMPLATE: '/submission/{user}/submission/{user}/mass'
    MINIO_BUCKET:           uploads
    OIDC_CLIENT_ID:         repository
    REPOSITORY_DIR:         /api/app/storage/repository
    SOLID_QUEUE_IN_PUMA:    'true'
    TZ:                     Asia/Tokyo

volumes:
  - /mnt/submission:/submission

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /app/api/public/web/assets

builder:
  arch: amd64
  context: ..

  args:
    APP_GID: 11370
    APP_UID: 2233

ssh:
  user: w3const

accessories:
  postgres:
    image: postgres:17

    options:
      user: 2233:11370

    env:
      secret:
        - POSTGRES_PASSWORD

      clear:
        POSTGRES_DB: repository
        TZ:          Asia/Tokyo

  minio:
    image: minio/minio:RELEASE.2023-12-07T04-16-00Z
    cmd: server /data --console-address :9001

    proxy:
      app_port: 9000

      healthcheck:
        path: /minio/health/live

    options:
      user: 2233:11370

    env:
      secret:
        - MINIO_ROOT_USER
        - MINIO_ROOT_PASSWORD

      clear:
        TZ: Asia/Tokyo

  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.6-r1-g0a3336c

    options:
      user: 2233:11370

    env:
      secret:
        - DBA_PASSWORD

      clear:
        VIRT_Client_SQL_PREFETCH_BYTES:         160000
        VIRT_Client_SQL_PREFETCH_ROWS:          10000
        VIRT_Parameters_DirsAllowed:            ., ../vad, /usr/share/proj, /database
        VIRT_Parameters_MaxDirtyBuffers:        130000
        VIRT_Parameters_NumberOfBuffers:        170000
        VIRT_SPARQL_MaxQueryCostEstimationTime: -1
        VIRT_SPARQL_MaxQueryExecutionTime:      300
        VIRT_SPARQL_MaxSortedTopRows:           100000
        VIRT_SPARQL_ResultSetMaxRows:           1000000

  validator:
    image: ddbj/ddbj_validator:main

    registry:
      server: ghcr.io
      username:
        - GHCR_USERNAME
      password:
        - GHCR_PASSWORD

    env:
      secret:
        - DDBJ_VALIDATOR_APP_POSTGRES_PASSWD
        - DDBJ_VALIDATOR_APP_POSTGRES_USER

      clear:
        DDBJ_VALIDATOR_APP_NAMED_GRAPHE_URI_TAXONOMY: http://ddbj.nig.ac.jp/ontologies/taxonomy-private
        DDBJ_VALIDATOR_APP_POSTGRES_TIMEOUT:          30
        DDBJ_VALIDATOR_APP_VALIDATOR_LOG_DIR:         /usr/src/ddbj_validator/logs
        DDBJ_VALIDATOR_APP_VIRTUOSO_ENDPOINT_MASTER:  http://repository-virtuoso:8890/sparql
        TZ:                                           Asia/Tokyo
