servers:
  web:
    hosts:
      - repository-staging 
    options:
      group_add: 60000

proxy:
  host: repository-dev.ddbj.nig.ac.jp

env:
  clear:
    MINIO_ENDPOINT:     https://repository-storage-dev.ddbj.nig.ac.jp
    OIDC_ISSUER_URL:    https://accounts-dev.ddbj.nig.ac.jp/realms/master
    SENTRY_CURRENT_ENV: staging
    DDBJ_VALIDATOR_URL: http://repository-validator:3000/api

volumes:
  - ./volumes/repository-staging/storage:/app/api/storage

accessories:
  postgres:
    host: repository-staging

    volumes:
      - ./volumes/repository-staging/postgres:/var/lib/postgresql/data

  minio:
    host: repository-staging

    volumes:
      - ./volumes/repository-staging/minio:/data

  virtuoso:
    host: repository-staging

    volumes:
      - ./volumes/repository-staging/virtuoso:/database

  validator:
    host: repository-staging
