- hosts: at026

  vars_prompt:
    - name: stage
      prompt: stage
      private: no

  tasks:
    - git:
        repo: https://github.com/ddbj/ddbj-repository.git
        dest: ~/ddbj-repository

    - command: compose/{{ stage }} up --build --detach
      args:
        chdir: ~/ddbj-repository
