name: CLI
on: push

permissions:
  contents: write

concurrency:
  group: cli-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cli

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - run: deno lint

  check:
    name: Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cli

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - run: deno check run.ts

  format:
    name: Format
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cli

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - run: deno fmt --check

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    defaults:
      run:
        working-directory: cli

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - run: ./compile

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            cli/dist/ddbj-repository-cli-aarch64-apple-darwin.zip
            cli/dist/ddbj-repository-cli-x86_64-apple-darwin.zip
            cli/dist/ddbj-repository-cli-x86_64-pc-windows-msvc.zip
            cli/dist/ddbj-repository-cli-x86_64-unknown-linux-gnu.zip
