name: Docker
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      APP_GID: 1000
      APP_UID: 1000

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - run: compose/local build
