name: test

on: push

jobs:
  rails:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        ports:
          - 5432:5432

        env:
          POSTGRES_DB: ddbj_repository_test
          POSTGRES_HOST_AUTH_METHOD: trust

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PGHOST: localhost
      PGUSER: postgres
      RAILS_ENV: test
      TZ: Japan

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: bin/rails db:prepare
      - run: bundle exec rspec
