name: test

on: push

jobs:
  rails:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        ports:
          - 5432:5432

        env:
          POSTGRES_DB: ddbj_repository_test
          POSTGRES_HOST_AUTH_METHOD: trust

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      BUNDLE_GITHUB__COM: x-access-token:${{ secrets._GITHUB_PAT }}
      BUNDLE_WITHOUT: development
      OIDC_ISSUER_URL: http://localhost:4567/auth/realms/master
      PGHOST: localhost
      PGUSER: postgres
      RAILS_ENV: test
      TZ: Japan

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: bundle exec submission-excel2xml download_xsd

      - run: bin/fakeoidc &
      - run: sleep 3
      - run: bin/rails db:prepare
      - run: bundle exec rspec
